// <auto-generated />
namespace CRUD_Operation_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Newly : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Newly));
        
        string IMigrationMetadata.Id
        {
            get { return "202106181100411_Newly"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
